# Generated by Django 6.0.4 on 2026-04-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("bass", "Guitare Basse (Loisirs)"),
                    ("acoustic", "Guitare Accompagnement (Bases)"),
                ],
                default="bass",
                max_length=50,
            ),
        ),
    ]
