# Generated by Django 6.0.4 on 2026-04-27 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0002_course_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="video_url",
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="Lien YouTube ou Vimeo", null=True
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Texte d'accompagnement ou tablatures"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="academy.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
